import * as THREE from 'three';
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import { hash01, clamp01 } from './Noise.ts';
import { PALETTE } from './CanyonSpec.ts';

/**
 * Broken stone — spoil from the digging, and the one honest way to finish a seam.
 *
 * Two jobs, and they are the same job. Where a bore's collar meets the terrain the two
 * surfaces are generated by different rules and cannot be made to agree exactly: on a
 * shallow wall the hole the terrain opens is thirty-odd units across while the bore's own
 * ring is twenty, so the collar spans the difference and that stretch reads as a crease
 * however carefully it is shaded. Rubble along the join does what rubble does at a real
 * excavation — it breaks the line, so the eye stops looking for one. And scattered around
 * a colony's feet it says the same thing the seam was accidentally saying: something dug
 * here.
 *
 * Deliberately *not* a fix for the underlying geometry. If a collar is ever wrong enough
 * to show a hole through to the skybox, stone on top of it hides a bug rather than a seam —
 * see the mouth work in `CanyonGenerator.wallHoleBoundary`, which is where that class of
 * problem gets solved.
 *
 * **No colliders, ever.** The whole codebase keeps one rule about this: what you see is
 * allowed to be leaner than what stops you, never the other way round. Loose stone at a
 * cavern mouth that could stop a lander would be a lander-sized problem hidden inside a
 * decoration, and the mouths these decorate are exactly where the flying is tightest.
 *
 * **Deterministic.** Every position, size and vertex comes from `hash01` keyed on the
 * campaign seed and the stone's own index, so a retry rebuilds the identical scatter —
 * the same rule the rest of the world generation keeps.
 */

/**
 * How much a block's three dimensions may differ from each other.
 *
 * The first version of this was a deformed octahedron, and it was wrong in a way worth
 * recording: pulling six vertices along their own axes and then flattening in y produces
 * thin, spiky shards, which at flight distance read as scraps of paper rather than as
 * stone. Rock that has been broken out of a face comes away in *blocks* — bedded, blocky,
 * with flat faces catching light at different angles — and a box says that with three
 * numbers.
 *
 * At 0.55 the range runs from a near-cube to a slab about three times longer than thick,
 * which is the spread a jointed rock face actually calves.
 */
const BLOCKY = 0.55;

/** How far a block may tip out of level. Small on purpose: spoil comes to rest, it does
 *  not stand on a corner, and a field of freely-rotated boxes reads as scattered dice. */
const TILT = 0.35;

/**
 * How far a block is sunk into whatever it is lying on, as a fraction of its own size.
 *
 * Stone sitting exactly *on* a surface is the tell that gives away scattered decoration:
 * every block meets the ground along one clean edge, none of them displaces anything, and
 * the whole scatter reads as objects placed on a plane rather than debris that came to
 * rest. Half-buried, the ground cuts each block at a different height and the intersection
 * does the work — which is also what makes the seam these are covering disappear, since a
 * block bridging the join is *in* both surfaces rather than balanced across them.
 *
 * Sunk by the stone's own scaled size rather than a fixed distance, so a big block beds in
 * proportionally and a small one is not swallowed whole.
 */
const SINK = 0.4;

/**
 * Off while the art direction is still an open question.
 *
 * Nothing here is known to be wrong — the seam rubble follows real boundary points, beds
 * into the surface and does the job it was built for. What is unresolved is whether the
 * canyon *wants* spoil at all, and that is a decision about how the world should read, not
 * a defect to fix. Left switched off rather than deleted: the generation and its
 * call sites are intact, the seams underneath are unchanged, and turning it back on is one
 * word.
 *
 * The thing worth remembering when that decision gets made: scatter anchored to a real
 * line (a bore's hole boundary, a pit's lip) works, because the geometry says where each
 * block goes. A free scatter over an area does not, because nothing does — see this
 * module's own header.
 */
const RUBBLE_ENABLED = false;

export interface RubbleSite {
  x: number;
  y: number;
  z: number;
  /** Nominal stone size. Individual stones vary around it by half again either way. */
  size: number;
}

/**
 * One block of broken stone.
 *
 * A box, with its three dimensions drawn independently so no two are the same brick, then
 * knocked a little out of true: the eight corners are each nudged by a hashed amount, which
 * is enough to stop the parallel faces reading as machined without turning the block back
 * into a shard. Spin freely about the vertical — nothing distinguishes one bearing from
 * another — but only tip slightly, because these are lying where they fell.
 */
function stone(site: RubbleSite, seed: number, index: number): THREE.BufferGeometry {
  const dim = (salt: number): number => site.size * (1 - BLOCKY + hash01(seed, index, salt, 91) * BLOCKY * 2);
  const geo = new THREE.BoxGeometry(dim(0), dim(1) * 0.8, dim(2));

  const pos = geo.attributes.position as THREE.BufferAttribute;
  for (let i = 0; i < pos.count; i++) {
    // Keyed on the rounded corner rather than the vertex index, so the three vertices a
    // box shares at each corner move together and the block stays closed.
    const key = (Math.sign(pos.getX(i)) + 2) * 9 + (Math.sign(pos.getY(i)) + 2) * 3 + Math.sign(pos.getZ(i)) + 2;
    const nudge = (s: number): number => (hash01(seed, index * 31 + key, s, 96) - 0.5) * site.size * 0.22;
    pos.setXYZ(i, pos.getX(i) + nudge(0), pos.getY(i) + nudge(1), pos.getZ(i) + nudge(2));
  }

  geo.rotateY(hash01(seed, index, 0, 92) * Math.PI * 2);
  geo.rotateX((hash01(seed, index, 0, 93) - 0.5) * TILT);
  geo.rotateZ((hash01(seed, index, 0, 94) - 0.5) * TILT);
  geo.translate(site.x, site.y - site.size * SINK, site.z);
  return geo;
}

/**
 * Scatters stone over a set of sites and merges the lot into one mesh.
 *
 * Returned rather than added to the scene by the caller's own bookkeeping, so whoever
 * owns the lifetime disposes it — `Colony` and `CanyonGenerator` both already track their
 * objects that way and neither should learn a second pattern for this.
 */
export function buildRubble(
  scene: THREE.Scene,
  sites: RubbleSite[],
  seed: number,
): THREE.Object3D | null {
  if (!RUBBLE_ENABLED || sites.length === 0) return null;

  const parts: THREE.BufferGeometry[] = [];
  const colors: number[] = [];
  const rockLow = new THREE.Color(PALETTE.rockLow);
  const rockMid = new THREE.Color(PALETTE.rockMid);

  sites.forEach((site, index) => {
    // A wide size spread is most of what makes a scatter read as broken rock rather than
    // as a product: a few big blocks anchor it, and the small ones fill between them.
    const scale = 0.55 + hash01(seed, index, 1, 95) ** 2 * 1.6;
    const geo = stone({ ...site, size: site.size * scale }, seed, index);
    parts.push(geo);
    // One tone per stone, not per vertex: a lump of rock is one lump of rock, and
    // shading within it is the flat-shaded facets' job. Spread across the same two
    // palette entries the shaft lining uses so spoil and bore read as the same stone.
    // Biased toward the lighter of the two: a freshly broken face is brighter than the
    // weathered wall it came out of, and the first pass — biased dark — left the blocks
    // reading as holes rather than as stone.
    const tone = rockMid.clone().lerp(rockLow, clamp01(hash01(seed, index, 2, 97)) * 0.35);
    for (let v = 0; v < geo.attributes.position.count; v++) colors.push(tone.r, tone.g, tone.b);
  });

  const merged = mergeGeometries(parts, false);
  for (const part of parts) part.dispose();
  if (!merged) return null;
  merged.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3));

  const mesh = new THREE.Mesh(
    merged,
    new THREE.MeshStandardMaterial({
      vertexColors: true,
      roughness: 1,
      metalness: 0,
      flatShading: true,
    }),
  );
  mesh.castShadow = true;
  mesh.receiveShadow = true;
  scene.add(mesh);
  return mesh;
}

/**
 * Stone along a line of points — a bore's hole boundary, in practice.
 *
 * Jittered off the line rather than sitting on it, because a row of stones spaced evenly
 * along a curve reads as a kerb. `spread` is how far off they may wander; `per` is how
 * many stones each point gets, so a boundary sampled coarsely still fills.
 */
export function rubbleAlong(
  points: Array<{ x: number; y: number; z: number }>,
  seed: number,
  opts: { size: number; spread: number; per?: number; salt?: number },
): RubbleSite[] {
  const per = opts.per ?? 2;
  const salt = opts.salt ?? 0;
  const sites: RubbleSite[] = [];
  points.forEach((p, i) => {
    for (let n = 0; n < per; n++) {
      const k = i * per + n;
      sites.push({
        x: p.x + (hash01(seed + salt, k, 0, 96) - 0.5) * opts.spread * 2,
        // Downward-only: an upward jitter undoes the bedding `SINK` just did, and a block
        // hovering above the join is the one thing this scatter cannot afford to show.
        y: p.y - hash01(seed + salt, k, 1, 97) * opts.spread * 0.5,
        z: p.z + (hash01(seed + salt, k, 2, 98) - 0.5) * opts.spread * 2,
        size: opts.size,
      });
    }
  });
  return sites;
}
